package it.kapfer.librepress.server;

/**
 * Represents a registered device that can be used for various management operations (often instead of authenticating with username and password), retrieve push
 * messages for downloading newspaper issues, and actually download them.
 * <p>
 * Implementors of the library are advised to store this information persistently, as it is required to perform subsequent operations. All registered devices
 * are also visible to the user (e.g. at <a href="https://www.pressreader.com/account">https://www.pressreader.com/account</a>).
 *
 * @param activationToken UUID assigned to the client during registration
 * @param clientId        numeric ID generated by the client during registration
 */
public record DeviceRegistration(String activationToken, int clientId) {
}
