package it.kapfer.librepress.server;

import java.util.Objects;

/**
 * Represents a registered device that can be used for various management operations (often instead of authenticating with username and password), retrieve push
 * messages for downloading newspaper issues, and actually download them.
 * <p>
 * Implementors of the library are advised to store this information persistently, as it is required to perform subsequent operations. All registered devices
 * are also visible to the user (e.g. at <a href="https://www.pressreader.com/account">https://www.pressreader.com/account</a>).
 */
public class DeviceRegistration {
    private final String activationToken;
    private final int clientId;

    /**
     * Creates a new device registration object.
     *
     * @param activationToken UUID assigned to the client during registration
     * @param clientId        numeric ID generated by the client during registration
     */
    public DeviceRegistration(String activationToken, int clientId) {
        this.activationToken = activationToken;
        this.clientId = clientId;
    }

    /**
     * {@return UUID assigned to the client during registration}
     */
    public String activationToken() {
        return activationToken;
    }

    /**
     * {@return numeric ID generated by the client during registration}
     */
    public int clientId() {
        return clientId;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        DeviceRegistration that = (DeviceRegistration) o;
        return clientId == that.clientId && Objects.equals(activationToken, that.activationToken);
    }

    @Override
    public int hashCode() {
        return Objects.hash(activationToken, clientId);
    }
}
